import { CalendarOff, Plus, Save, Trash2 } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Badge, Button, Card, Empty, Field, Input, Notice, PageHeader } from '../components/ui';
import { api } from '../lib/api';

const days=['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'] as const;
type Day=typeof days[number];type Hours={dayOfWeek:Day;opensAt:string;closesAt:string};
type Override={overrideDate:string;isClosed:boolean;opensAt:string|null;closesAt:string|null;reason:string|null};
export function AvailabilityPage(){const [hours,setHours]=useState<Hours[]>([]);const [overrides,setOverrides]=useState<Override[]>([]);const [message,setMessage]=useState('');const [draft,setDraft]=useState<Override>({overrideDate:'',isClosed:true,opensAt:null,closesAt:null,reason:null});
const load=()=>Promise.all([api<{hours:Hours[]}>('/business/hours'),api<{overrides:Override[]}>('/business/overrides')]).then(([a,b])=>{setHours(a.hours.map(h=>({...h,opensAt:h.opensAt.slice(0,5),closesAt:h.closesAt.slice(0,5)})));setOverrides(b.overrides)});useEffect(()=>{void load()},[]);
const row=(day:Day)=>hours.find(h=>h.dayOfWeek===day);const toggle=(day:Day,on:boolean)=>setHours(on?[...hours,{dayOfWeek:day,opensAt:'09:00',closesAt:'17:00'}]:hours.filter(h=>h.dayOfWeek!==day));const changeTime=(day:Day,key:'opensAt'|'closesAt',value:string)=>setHours(hours.map(h=>h.dayOfWeek===day?{...h,[key]:value}:h));
const saveHours=async()=>{await api('/business/hours',{method:'PUT',body:JSON.stringify({hours})});setMessage('Weekly hours saved.')};const saveOverride=async()=>{await api(`/business/overrides/${draft.overrideDate}`,{method:'PUT',body:JSON.stringify(draft)});setDraft({overrideDate:'',isClosed:true,opensAt:null,closesAt:null,reason:null});await load();setMessage('Schedule override added.')};const remove=async(date:string)=>{await api(`/business/overrides/${date}`,{method:'DELETE'});setOverrides(overrides.filter(x=>x.overrideDate.slice(0,10)!==date.slice(0,10)))};
return <><PageHeader title="Availability" description="Set weekly hours and date-specific exceptions."/>{message&&<Notice>{message}</Notice>}<div className="two-column"><Card><div className="section-head"><div><h2>Weekly business hours</h2><p>Closed days simply have no active hours.</p></div></div><div className="hours-list">{days.map(day=>{const current=row(day);return <div className="hours-row" key={day}><label className="check"><input type="checkbox" checked={!!current} onChange={e=>toggle(day,e.target.checked)}/><strong>{day[0]+day.slice(1).toLowerCase()}</strong></label>{current?<div className="time-pair"><Input type="time" value={current.opensAt} onChange={e=>changeTime(day,'opensAt',e.target.value)}/><span>to</span><Input type="time" value={current.closesAt} onChange={e=>changeTime(day,'closesAt',e.target.value)}/></div>:<Badge>Closed</Badge>}</div>})}</div><div className="form-actions"><Button onClick={()=>void saveHours()}><Save size={17}/>Save hours</Button></div></Card><div><Card><div className="section-head"><div><h2>Add schedule override</h2><p>Holidays, half-days, and special opening hours.</p></div><CalendarOff size={21}/></div><div className="form-grid"><Field label="Date"><Input type="date" value={draft.overrideDate} onChange={e=>setDraft({...draft,overrideDate:e.target.value})}/></Field><Field label="Reason"><Input value={draft.reason??''} onChange={e=>setDraft({...draft,reason:e.target.value||null})} placeholder="Public holiday"/></Field></div><label className="check override-check"><input type="checkbox" checked={draft.isClosed} onChange={e=>setDraft({...draft,isClosed:e.target.checked,opensAt:e.target.checked?null:'09:00',closesAt:e.target.checked?null:'13:00'})}/>Closed all day</label>{!draft.isClosed&&<div className="form-grid"><Field label="Opens"><Input type="time" value={draft.opensAt??''} onChange={e=>setDraft({...draft,opensAt:e.target.value})}/></Field><Field label="Closes"><Input type="time" value={draft.closesAt??''} onChange={e=>setDraft({...draft,closesAt:e.target.value})}/></Field></div>}<Button disabled={!draft.overrideDate||(!draft.isClosed&&(!draft.opensAt||!draft.closesAt))} onClick={()=>void saveOverride()}><Plus size={17}/>Add override</Button></Card><Card className="override-list"><h2>Upcoming exceptions</h2>{overrides.length?overrides.map(item=><div className="list-row" key={item.overrideDate}><div className="grow"><strong>{new Date(item.overrideDate).toLocaleDateString(undefined,{dateStyle:'medium'})}</strong><small>{item.isClosed?'Closed all day':`${item.opensAt?.slice(0,5)} – ${item.closesAt?.slice(0,5)}`} · {item.reason||'Special hours'}</small></div><button className="icon-button danger" onClick={()=>void remove(item.overrideDate.slice(0,10))}><Trash2 size={17}/></button></div>):<Empty title="No upcoming overrides" text="Special dates will appear here."/>}</Card></div></div></>}
