import { AtSign, Globe2, Instagram, Mail, MessageCircle, Phone, Save } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Badge, Button, Card, Field, Input, Notice, PageHeader } from '../components/ui';
import { api } from '../lib/api';
import type { Channel } from '../types';

type ChannelConfig={channel:Channel;enabled:boolean;provider:string|null;externalAccountId:string|null;metadata:Record<string,unknown>};
const icons={WHATSAPP:MessageCircle,PHONE:Phone,SMS:AtSign,EMAIL:Mail,INSTAGRAM:Instagram,WEBSITE:Globe2};
export function ChannelsPage(){const [items,setItems]=useState<ChannelConfig[]>([]);const [saved,setSaved]=useState('');useEffect(()=>{api<{channels:ChannelConfig[]}>('/business/channels').then(r=>setItems(r.channels))},[]);const update=(index:number,key:keyof ChannelConfig,value:unknown)=>setItems(items.map((item,i)=>i===index?{...item,[key]:value}:item));const save=async(index:number)=>{const item=items[index];const r=await api<{channel:ChannelConfig}>(`/business/channels/${item.channel}`,{method:'PUT',body:JSON.stringify(item)});setItems(items.map((x,i)=>i===index?r.channel:x));setSaved(item.channel)};
return <><PageHeader title="Channels" description="Connect only the places where your customers contact you."/>{saved&&<Notice>{saved} configuration saved.</Notice>}<div className="channel-grid">{items.map((item,index)=>{const Icon=icons[item.channel];return <Card className="channel-card" key={item.channel}><div className="channel-title"><span><Icon size={22}/></span><div><h2>{item.channel[0]+item.channel.slice(1).toLowerCase()}</h2><Badge tone={item.enabled?'green':'neutral'}>{item.enabled?'Enabled':'Disabled'}</Badge></div><label className="mini-toggle"><input type="checkbox" checked={item.enabled} onChange={e=>update(index,'enabled',e.target.checked)}/><span className="toggle"/></label></div><Field label="Provider"><Input placeholder="e.g. Twilio, Meta" value={item.provider??''} onChange={e=>update(index,'provider',e.target.value||null)}/></Field><Field label="External account ID"><Input value={item.externalAccountId??''} onChange={e=>update(index,'externalAccountId',e.target.value||null)}/></Field><Button className="button-secondary" onClick={()=>void save(index)}><Save size={16}/>Save channel</Button></Card>})}</div></>}
