import { Plus, Search, Trash2, UserPlus, X } from 'lucide-react';
import { useEffect, useState, type FormEvent } from 'react';
import { Badge, Button, Card, Empty, Field, Input, PageHeader, Select } from '../components/ui';
import { api } from '../lib/api';
import type { Channel, Customer } from '../types';

const channels:Channel[]=['PHONE','WHATSAPP','SMS','EMAIL','INSTAGRAM','WEBSITE'];
export function CustomersPage(){const [items,setItems]=useState<Customer[]>([]);const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [form,setForm]=useState({name:'',channel:'EMAIL' as Channel,identifier:'',displayName:''});const load=()=>api<{customers:Customer[]}>(`/customers?limit=100&search=${encodeURIComponent(search)}`).then(r=>setItems(r.customers));useEffect(()=>{const timer=setTimeout(()=>void load(),250);return()=>clearTimeout(timer)},[search]);const submit=async(e:FormEvent)=>{e.preventDefault();await api('/customers',{method:'POST',body:JSON.stringify({name:form.name||null,identities:form.identifier?[{channel:form.channel,identifier:form.identifier,displayName:form.displayName||null,isPrimary:true}]:[]})});setForm({name:'',channel:'EMAIL',identifier:'',displayName:''});setOpen(false);await load()};const remove=async(id:string)=>{if(!confirm('Delete this customer? Customers with appointment history cannot be deleted.'))return;await api(`/customers/${id}`,{method:'DELETE'});await load()};
return <><PageHeader title="Customers" description="Minimal customer records with channel-specific identities." action={<Button onClick={()=>setOpen(!open)}>{open?<X size={17}/>:<UserPlus size={17}/>} {open?'Close':'Add customer'}</Button>}/>{open&&<Card className="inline-create"><form onSubmit={submit}><div className="form-grid"><Field label="Customer name"><Input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Optional"/></Field><Field label="Identity channel"><Select value={form.channel} onChange={e=>setForm({...form,channel:e.target.value as Channel})}>{channels.map(c=><option key={c}>{c}</option>)}</Select></Field></div><div className="form-grid"><Field label="Identifier" hint={form.channel==='INSTAGRAM'?'Use immutable Instagram User ID, not username.':'Phone, email, or website session ID.'}><Input value={form.identifier} onChange={e=>setForm({...form,identifier:e.target.value})}/></Field><Field label="Display name" hint="Instagram username belongs here."><Input value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></Field></div><Button><Plus size={17}/>Create customer</Button></form></Card>}<Card><div className="table-toolbar"><div><h2>Customer directory</h2><p>Identities stay normalized by channel.</p></div><div className="search-box"><Search size={17}/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name or identity"/></div></div>{items.length?<div className="customer-list">{items.map(item=><div className="customer-row" key={item.id}><span className="avatar large">{item.name?.[0]?.toUpperCase()||'?'}</span><div className="grow"><strong>{item.name||'Unnamed customer'}</strong><div className="identity-list">{item.identities.map(identity=><span key={identity.id}><Badge tone="blue">{identity.channel}</Badge>{identity.identifier}{identity.displayName&&<small> · {identity.displayName}</small>}</span>)}</div></div><button className="icon-button danger" onClick={()=>void remove(item.id)}><Trash2 size={17}/></button></div>)}</div>:<Empty title="No customers found" text="Add a customer to start building your directory."/>}</Card></>}
