import { CalendarCheck2, ContactRound, MessageSquareText, RadioTower, TrendingUp, type LucideIcon } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card, Empty, PageHeader, Spinner, Badge } from '../components/ui';
import { api, formatDate } from '../lib/api';
import type { Appointment } from '../types';

type Summary={metrics:{appointmentsToday:number;upcomingAppointments:number;openConversations:number;totalCustomers:number;enabledChannels:number};upcoming:Appointment[]};
export function DashboardPage(){const [data,setData]=useState<Summary|null>(null);useEffect(()=>{api<Summary>('/dashboard/summary').then(setData)},[]);if(!data)return <Spinner/>;
  const metrics:{label:string;value:number;Icon:LucideIcon;tone:string}[]=[{label:'Appointments today',value:data.metrics.appointmentsToday,Icon:CalendarCheck2,tone:'violet'},{label:'Next 7 days',value:data.metrics.upcomingAppointments,Icon:TrendingUp,tone:'blue'},{label:'Open conversations',value:data.metrics.openConversations,Icon:MessageSquareText,tone:'amber'},{label:'Total customers',value:data.metrics.totalCustomers,Icon:ContactRound,tone:'green'}];
  return <><PageHeader title="Good to see you" description="Here’s what is happening across your business today." action={<Link className="button" to="/appointments">New appointment</Link>}/><div className="metrics">{metrics.map(({label,value,Icon,tone})=><Card key={label} className={`metric metric-${tone}`}><span className="metric-icon"><Icon size={21}/></span><div><strong>{value}</strong><span>{label}</span></div></Card>)}</div><div className="dashboard-grid"><Card><div className="section-head"><div><h2>Upcoming appointments</h2><p>Your next confirmed and pending bookings.</p></div><Link to="/appointments">View all</Link></div>{data.upcoming.length?<div className="list">{data.upcoming.map(item=><div className="list-row" key={item.id}><span className="date-tile"><strong>{new Date(item.scheduledStart).getDate()}</strong><small>{new Date(item.scheduledStart).toLocaleString(undefined,{month:'short'})}</small></span><div className="grow"><strong>{item.customerName||'Unnamed customer'}</strong><small>{formatDate(item.scheduledStart)}</small></div><Badge tone={item.status==='CONFIRMED'?'green':'amber'}>{item.status}</Badge></div>)}</div>:<Empty title="No upcoming appointments" text="New bookings will appear here."/>}</Card><Card className="setup-card"><div className="section-head"><div><h2>Workspace readiness</h2><p>Finish the essentials before going live.</p></div><RadioTower size={22}/></div><div className="readiness"><div><span>Enabled channels</span><strong>{data.metrics.enabledChannels} / 6</strong></div><progress max="6" value={data.metrics.enabledChannels}/><Link className="button button-secondary" to="/channels">Configure channels</Link><Link className="text-link" to="/availability">Review availability</Link></div></Card></div></>}
